import { randomUUID,createHash } from "node:crypto";
import fs from "node:fs/promises";
import { db } from "./db";
import { normalizeName } from "./excel-import";
import { parseHistoricalWorkbook } from "./historical-import";
import { ensureUploadDirectory,uploadPath } from "./import-storage";
type EmployeeRow={id:string;normalized_name:string;full_name:string};
const nameAliases:Array<[string,string]>=[["ดนุกานต์","ตั้ง"],["อัษฎาพร","บอล"],["วรรณษณ์","แนน"],["จริยา","วรรณษรณ์"],["พัชระ","เม่น"],["วัชระ","นุก"],["โชคลิขิต","เบียร์"],["สุภนัย","เปา"],["ภาณุวัฒน์","บอย"],["อดิศักดิ์","เก็ต"],["บรรจง","บรรจง"]];
function personKey(value:string){return normalizeName(value).replace(/^(นาย|นางสาว|นาง)/,"").replace(/[.]/g,"");}
function findEmployee(sourceName:string,employees:EmployeeRow[]){const source=personKey(sourceName);const direct=employees.filter(employee=>{const candidate=personKey(employee.full_name||employee.normalized_name);return candidate===source||candidate.includes(source)||source.includes(candidate);});if(direct.length===1)return direct[0];const aliases=nameAliases.flatMap(([left,right])=>{const a=personKey(left),b=personKey(right);return source.includes(a)?[b]:source.includes(b)?[a]:[];});const aliasMatches=employees.filter(employee=>{const candidate=personKey(employee.full_name||employee.normalized_name);return aliases.some(alias=>candidate.includes(alias)||alias.includes(candidate));});return aliasMatches.length===1?aliasMatches[0]:null;}
/** Imports only start dates and leave records. Monthly Excel is the sole source of payroll. */
export async function importHistoricalAnnual({companyId,userId,filename,buffer}:{companyId:string;userId:string;filename:string;buffer:Buffer}){if(buffer.length===0||buffer.length>25*1024*1024)throw new Error("ขนาดไฟล์ไม่อยู่ในขอบเขตที่รองรับ");const sha256=createHash("sha256").update(buffer).digest("hex"),storageKey=`${randomUUID()}.xlsx`;await ensureUploadDirectory();await fs.writeFile(uploadPath(storageKey),buffer,{mode:0o600});try{const parsed=await parseHistoricalWorkbook(uploadPath(storageKey)),client=await db().connect();try{await client.query("BEGIN");const duplicate=await client.query("SELECT id FROM historical_imports WHERE company_id=$1 AND sha256=$2",[companyId,sha256]);if(duplicate.rowCount)throw new Error("ไฟล์ Annual Excel นี้ถูกนำเข้าแล้ว");const history=await client.query<{id:string}>("INSERT INTO historical_imports(company_id,original_filename,storage_key,sha256,imported_by,metadata) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[companyId,filename,storageKey,sha256,userId,JSON.stringify({sheets:parsed.sheets,years:parsed.years,scope:"employment_and_leave"})]);const records=await client.query<EmployeeRow>("SELECT id,normalized_name,full_name FROM employees WHERE company_id=$1 FOR UPDATE",[companyId]);let matched=0,leave=0,startDates=0;const unmatched:string[]=[];for(const source of parsed.employees){const employee=findEmployee(source.name,records.rows);if(!employee){unmatched.push(source.name);continue;}matched++;if(source.startDate){const updated=await client.query("UPDATE employees SET hire_date=COALESCE(hire_date,$3),updated_at=now() WHERE id=$1 AND company_id=$2 AND hire_date IS NULL",[employee.id,companyId,source.startDate]);startDates+=updated.rowCount||0;}for(const item of source.leave){await client.query("INSERT INTO leave_records(company_id,employee_id,date_from,date_to,leave_type,days,reason,source_type,created_by,note) VALUES($1,$2,$3,$4,$5,$6,$7,'imported',$8,$9)",[companyId,employee.id,item.dateFrom,item.dateTo,item.type,item.days,item.reason||null,userId,`Annual historical import ${history.rows[0].id}`]);leave++;}}await client.query("INSERT INTO audit_logs(company_id,actor_id,action,entity_type,entity_id,after_data) VALUES($1,$2,'import','historical_import',$3,$4)",[companyId,userId,history.rows[0].id,JSON.stringify({years:parsed.years,matched,startDates,leave,unmatched:unmatched.length,scope:"employment_and_leave"})]);await client.query("COMMIT");return {years:parsed.years,employees:parsed.employees.length,matched,startDates,leave,unmatched:unmatched.length};}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}catch(error){await fs.unlink(uploadPath(storageKey)).catch(()=>{});throw error;}}