param([Parameter(Mandatory=$true)][string]$TemplatePath,[Parameter(Mandatory=$true)][string]$DataPath,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop'
function Norm($v){if($null -eq $v){return ''};return (($v.ToString()).ToLowerInvariant() -replace '[\s\-_\/().:+]+','')}
function Txt($s,$r,$c){return $s.Cells.Item($r,$c).Text.ToString().Trim()}
function Formula($c){$value=$c.Formula;return $value -is [string] -and $value.StartsWith("=")}
function Map($m,$k){$p=$m.PSObject.Properties[$k];if($p){return $p.Value};return $null}
function SetValue($c,$v){if(-not(Formula $c)){$c.Value2=$v}}
function SetDate($c,$v){if($v -and -not(Formula $c)){$c.Value=[datetime]::ParseExact($v,'yyyy-MM-dd',[Globalization.CultureInfo]::InvariantCulture)}}
function ClearValues($s,$r1,$r2,$c1,$c2){for($r=$r1;$r -le $r2;$r++){for($c=$c1;$c -le $c2;$c++){$cell=$s.Cells.Item($r,$c);if(-not(Formula $cell)){$cell.Value2=$null}}}}
function SafeName($name,$index,$used){$safe=($name -replace '[\\/\?\*\[\]:]',' ').Trim();if(!$safe){$safe="Employee $index"};if($safe.Length -gt 31){$safe=$safe.Substring(0,31)};$candidate=$safe;$n=2;while($used.ContainsKey($candidate)){$candidate=$safe.Substring(0,[Math]::Min(27,$safe.Length))+" ($n)";$n++};$used[$candidate]=$true;return $candidate}
function FillSummary($s,$data){ClearValues $s 3 14 2 5;$rows=@{};foreach($row in $data.summary){$rows[[int]$row.month]=$row};for($m=1;$m -le 12;$m++){$row=$rows[$m];if($null -eq $row){continue};$r=$m+2;SetValue $s.Cells.Item($r,2) ([double]$row.employeeGross);SetValue $s.Cells.Item($r,3) ([double]$row.directorGross);SetValue $s.Cells.Item($r,4) ([double]$row.employeeBonus);SetValue $s.Cells.Item($r,5) ([double]$row.directorBonus);SetValue $s.Cells.Item($r,6) ([double]$row.total)} }
function FillEmployee($s,$employee,$data){$last=$s.UsedRange.Columns.Count;ClearValues $s 3 14 2 $last;$entries=@{};foreach($e in $employee.entries){$entries[[int]$e.month]=$e};for($m=1;$m -le 12;$m++){$e=$entries[$m];if($null -eq $e){continue};for($c=2;$c -le $last;$c++){$key=Norm(Txt $s 2 $c);$code=Map $data.itemHeaderCodes $key;$special=Map $data.specialHeaderCodes $key;$cell=$s.Cells.Item($m+2,$c);if($code){$value=Map $e.items $code;if($null -ne $value){SetValue $cell ([double]$value)}}elseif($special -eq 'gross'){SetValue $cell ([double]$e.gross)}elseif($special -eq 'deductions'){SetValue $cell ([double]$e.deductions)}elseif($special -eq 'net'){SetValue $cell ([double]$e.net)}}}
 $hireRow=0;for($r=15;$r -le $s.UsedRange.Rows.Count;$r++){if((Txt $s $r 1).Contains($data.labels.hireDate)){$hireRow=$r;break}};if($hireRow){SetDate $s.Cells.Item($hireRow,2) $employee.hireDate}
 $leaveDate=0;$leaveCols=@{};for($c=2;$c -le $last;$c++){$key=Norm(Txt $s 2 $c);if($data.leaveDateHeaderKeys -contains $key){$leaveDate=$c};$kind=Map $data.leaveHeaderCodes $key;if($kind){$leaveCols[$kind]=$c}};if($leaveDate){ClearValues $s 3 16 $leaveDate $last;$i=0;foreach($leave in $employee.leaves){if($i -ge 14){break};$r=3+$i;SetDate $s.Cells.Item($r,$leaveDate) $leave.dateFrom;$c=$leaveCols[$leave.type];if($c){SetValue $s.Cells.Item($r,$c) ([double]$leave.days)};if($last -gt $leaveDate){SetValue $s.Cells.Item($r,$last) $leave.reason};$i++}}
 $s.Cells.Item(1,1).Value2="$($data.labels.employeeTitle) $($employee.fullName) $([int]$data.year+543)"
}
$template=(Resolve-Path -LiteralPath $TemplatePath).Path;$output=[IO.Path]::GetFullPath($OutputPath);$parent=Split-Path -Parent $output;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Path $parent | Out-Null};if(Test-Path $output){Remove-Item $output -Force};$data=Get-Content -Encoding UTF8 -Raw -LiteralPath $DataPath | ConvertFrom-Json
$excel=$null;$book=$null
try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false;$excel.AskToUpdateLinks=$false;$excel.EnableEvents=$false;$excel.AutomationSecurity=3;$excel.Calculation=-4135;$excel.CalculateBeforeSave=$false;Copy-Item $template $output -Force;Unblock-File $output;$book=$excel.Workbooks.Open($output,0,$false);$templates=@();for($i=1;$i -le $book.Worksheets.Count;$i++){$s=$book.Worksheets.Item($i);if($s.UsedRange.Rows.Count -ge 17 -and (Txt $s 2 1).Length -gt 0 -and (Txt $s 2 2).Length -gt 0){$templates+=@($s)}};if(!$templates.Count){throw 'Employee template not found'};if($templates.Count -lt $data.employees.Count){throw "Template has insufficient employee sheets"};$sheets=@($templates | Sort-Object {$_.UsedRange.Columns.Count} -Descending | Select-Object -First $data.employees.Count);$needed=@($sheets | ForEach-Object {$_.Name});foreach($s in $templates){if($needed -notcontains $s.Name){$s.Delete()}};$summary=$null;for($i=1;$i -le $book.Worksheets.Count;$i++){if($needed -notcontains $book.Worksheets.Item($i).Name){$summary=$book.Worksheets.Item($i);break}};$used=@{};for($i=0;$i -lt $data.employees.Count;$i++){$s=$sheets[$i];$s.Name=SafeName $data.employees[$i].fullName ($i+1) $used;FillEmployee $s $data.employees[$i] $data};if($summary){FillSummary $summary $data;$summary.Cells.Item(1,1).Value2="$($data.labels.companySummaryTitle) $([int]$data.year+543)"};$book.Save();$book.Close($true);$book=$null}finally{if($book){$book.Close($false)};if($excel){$excel.Quit();[void][Runtime.InteropServices.Marshal]::ReleaseComObject($excel)};[GC]::Collect();[GC]::WaitForPendingFinalizers()}
